/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import com.google.gson.Gson;
import java.util.Arrays;

public class App {
    public static void main(String[] args) {
      Gson gson = new Gson();
      System.out.println(gson.toJson(Arrays.asList(1, 2, 3)));
    }
}
